[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300
numReplicas = 1

[deploy.env]
PORT = "$PORT"
NODE_ENV = "production"
HOST = "0.0.0.0"

[[services]]
internal_port = "$PORT"
protocol = "http"
auto_deploy = true

[nixpacks]
nodejs_version = "18"